### PR TITLE
Fix: 913 double resume picker

### LINKED ISSUE #913: File upload opens two select file dialogs when clicked
Windows 10, Microsoft Edge

New file upload #868 opens two select file dialog windows, only using file selected from second one

### PR DESCRIPTION
**Pull request by jamesxu123**
### Tickets:

- HCK-#913

### List of changes:

- Updated react-dropzone
- Fixed double picker problem
- Improve "View Resume" button visuals
- Maintain filename on resume component through page navigation
- Fixed resume set logic on page navigation

### Type of change:

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### PR Checklist:

- [x] Merged `develop` branch (before testing)
- [x] Linted my code locally
- [ ] Listed change(s) in the Changelog
- [x] Tested all links in project relevant browsers
- [x] Tested all links on different screen sizes
- [x] Referenced all useful info (issues, tasks, etc)

### Screenshots:

fixes #913

### CODE REVIEW

**Comment by jamesxu123** [comment]
There's an additional problem with the resume when editing the application where the file name doesn't update in the review tab if you change the resume during the edit process more than once. It seems that the correct file is set in the Formik component, I'll keep debugging to see where the problem is.

**Review by logan-r — APPROVED** [review]
LGTM

**Comment by jamesxu123** [comment]
I think I found the root issue of the resume set thing. It was only checking if `resume` and `values.resume` were `null` and not if they were different.

**Review by logan-r — APPROVED** [review]
Looks good!

**Pull request merged**
