### PR TITLE
Feature/247 stats component

### PR DESCRIPTION
**Pull request by pierreTklein**
Preliminary capabilities for stats component, viewable on /admin/search

Implements #247 

hackerAPI branch must be set to feature/274-statsQuery

### CODE REVIEW

**Comment by pierreTklein** [comment]
Sorry, this was a premature PR when I was super tired last night-- mainly looking for suggestions about  UX

**Comment by pierreTklein** [comment]
Currently the stats show a bunch of pie charts, and some of the pie charts are clickable which redirect to the search page

**Comment by pierreTklein** [comment]
Hmm, maybe the search component and the stats component should be combined?

**Comment by pierreTklein** [comment]
@krubenok 
image

**Comment by pierreTklein** [comment]
## Table component

screen shot 2019-01-07 at 8 54 45 pm_censored

## Stats component

**Comment by pierreTklein** [comment]
@ailishm

**Comment by pierreTklein** [comment]
Can I merge this in as is? @krubenok @erickzhao

**Comment by erickzhao** [comment]
@pierreTklein I still haven't run it yet. Is there an easy way for me to generate fake data to test locally?

**Comment by pierreTklein** [comment]
Hmm you could try running with non-fake data by changing CORS from:
```javascript
    // TODO: change this when necessary
    corsOptions = {
        origin: [`https://${process.env.FRONTEND_ADDRESS_DEPLOY}`, `https://docs.mchacks.ca`],
        credentials: true
    };
```

to:
```javascript
    // TODO: change this when necessary
    corsOptions = {
        origin: [`http://${process.env.FRONTEND_ADDRESS_DEV}`, `https://${process.env.FRONTEND_ADDRESS_DEPLOY}`, `https://docs.mchacks.ca`],
        credentials: true
    };
```

and running `npm run start`

**Comment by pierreTklein** [comment]
Oh Hmm, it seems like the UX is not working out for your browser :(. The presented numbers should change on hover. In addition, clicking on the pie should apply that filter, but then clicking again should remove that filter:
[Image from Gyazo](https://gyazo.com/0156c59dee5eb380d56b35bd15d2ca60)

**Comment by erickzhao** [comment]
Update 🔥 🦊  issue

**Comment by pierreTklein** [comment]
image

**Comment by pierreTklein** [comment]
We haven't tested for Sponsor integration, so I feel a little hesitant about merging this one in

**Pull request closed without merging**
