### PR TITLE
Keep background image on mobile

### LINKED ISSUE #177: No mobile background on dashboard
The background on the login page stays on mobile but the background on the dashboard disappears once the screen gets too small.

image
image

Maybe just add the same conditions so there's no resizing to fit screen but also isn't blank?

### PR DESCRIPTION
**Pull request by pierreTklein**
Fixes #177 

# Screenshot
localhost_1337_ iphone x

### CODE REVIEW

**Comment by pierreTklein** [comment]
Rip. Overflow doesn't fix this either

**Comment by loreina** [comment]
I'm having the same issue rn with the static site 😢

**Comment by erickzhao** [comment]
https://stackoverflow.com/questions/3225102/css-overflow-hidden-with-absolute-position

Seems like an issue with the parent container not being `position: relative`. You could try to play around with the DOM, or we could make a mobile-friendly version of the SVG.

**Comment by pierreTklein** [comment]
Alright so I had a look at the mobile registration on figma, and noticed that we're using a different svg: 
https://www.figma.com/file/RessZCNwQN9HXXz1rQyPZDbk/Registration-system-mobile?node-id=0%3A1

**Comment by loreina** [comment]
@pierreTklein I think it's okay at this point lol but if you want to change it, go for it

**Comment by pierreTklein** [comment]
Can you check on it now?

**Comment by pierreTklein** [comment]
@loreina can you have a look?

**Pull request closed without merging**
