### PR TITLE
build: Upgrading dependencies for compatibility with Node 20 and general maintenance

### PR DESCRIPTION
**Pull request by msohaill**
### List of changes:

- Upgrading all dependencies to latest stable versions (where possible)
- Several API adjustments required, but functionality is retained (as far as I was able to test)
- Dependency override added for react-table in order to be compatible with React 18. Seems that this dependency has changed quite a bit so we are forced remain at the older version and override the React dependency
- styled-components is fixed to v5 since v6 typing is broken currently :(
- formik is fixed at 2.1.0 as newer versions interfere with weird reset form setup we have for multi-page forms (ex., Hacker application)
- Various unused dependencies removed
- Did a lint of the files (seems its been a while), so a lot of the changes are just that

### Type of change:

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that ~would~ _may_ cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How did you do this?
Basically just using `ncu -u` (npm-check-upgrade) to update all dependencies and then updating system Node version and then doing some testing/tinkering. Read up on the various package APIs for those that were broken.

### How to test:
Each working component needs to be tested to ensure no functionality has been broken. Unfortunately, my back end doesn't seem to be set up completely? Or perhaps it is just meant to be like that, so I am not able to test completely. But, I have test what I can and everything seems to be great!

### PR Checklist:

- [ ] Merged `develop` branch (before testing)
- [x] Linted my code locally
- [ ] Listed change(s) in the Changelog
- [ ] Tested all links in project relevant browsers
- [ ] Tested all links on different screen sizes
- [ ] Referenced all useful info (issues, tasks, etc)

### CODE REVIEW

**Comment by jackyyzhang03** [comment]
Changes seem to break search filters for me (Search Hackers). For example, if I try to filter by school, I have to click the button more than once for the changes to be reflected. This does not appear to be the case previously.

**Comment by jackyyzhang03** [comment]
> Unfortunately, my back end doesn't seem to be set up completely?
Not sure about this but we can check it out together

**Comment by msohaill** [comment]
> Changes seem to break search filters for me (Search Hackers). For example, if I try to filter by school, I have to click the button more than once for the changes to be reflected. This does not appear to be the case previously.

Debugged and seems setState was used incorrectly somewhere and the synchronicity errors did not surface in React 16 but does in 18. Fixed it and I'll see if there's anywhere else something similar happens

**Review by jackyyzhang03 — APPROVED** [review]
LGTM

**Pull request merged**
