### PR TITLE
Feat/868 resume component

### LINKED ISSUE #868: Restyle resume component
Stylistic changes to resume component, should look like so: [Image from Gyazo](https://gyazo.com/7568adcf2ba399d69e0259e77f881cfa)

Should also have link to view already uploaded resume somewhere if applicant has already done so.

### PR DESCRIPTION
**Pull request by jamesxu123**
### Tickets:

- HCK-#868

### List of changes:

- New resume component style

### Type of change:

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### PR Checklist:

- [x] Merged `develop` branch (before testing)
- [x] Linted my code locally
- [ ] Listed change(s) in the Changelog
- [ ] Tested all links in project relevant browsers
- [x] Tested all links on different screen sizes
- [x] Referenced all useful info (issues, tasks, etc)

### Screenshots:
image
image
image

close #868

### CODE REVIEW

**Comment by jamesxu123** [comment]
Before any merges, I had a couple of questions:

1. Is the max file size 1MB? Not sure if the Figma was just for show.
2. Are we limited to PDFs only? I just kind of assumed so, but I can always change it.

**Comment by logan-r** [comment]
1. Let's stick with 4MB
2. Yeah, pdf only

**Review by logan-r — COMMENTED** [review]
Is it possible to get rid of the inner dotted outline shown in some of the screenshots? (Think this is a focus state in firefox or something right?)

Also, is there a way for them to check which file they opened? (e.g. below box a "resume.pdf" link appears opens link to uploaded resume in new tab)

**Comment by jamesxu123** [comment]
I fixed the outline, it was a focus state thing.

About seeing the file, do you mean like a local link to open the file that they have selected? I don't think the resume is uploaded until the submit the form. I do have a small subtitle with the file name already, but I can add that button if needed.

**Review by logan-r — APPROVED** [review]
Looks great!

We could consider adding link to selected file at file:// uri, not sure if that's necessary tho

**Comment by jamesxu123** [comment]
Yeah personally I think having the file name should be good. I’m not sure if I’ve seen a file:// uri for file uploads elsewhere.

**Comment by logan-r** [comment]
Yeah did a bit of invistigating and it appears that we can't link to local `file://` uri before uploading because that's a security flaw - we could encode the file using `FileReader` then use `data://` uri to link to it but that's too much effort for a very minor feature

**Pull request merged**
