### PR TITLE
Feature/status page

### PR DESCRIPTION
**Pull request by RohitGarudadri**
### Tickets:

- HCK-

### List of changes:

- Status page displays appropriate message based on hacker status

### Type of change:

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)

### How did you do this?

If statements all the way down

### How to test:

Change hackerstatus in DBCompass and view what status page says.

### PR Checklist:

- [x] Merged `develop` branch (before testing)
- [x] Linted my code locally
- [x] Listed change(s) in the Changelog
- [x] Tested all links in project relevant browsers
- [x] Tested all links on different screen sizes
- [x] Referenced all useful info (issues, tasks, etc)

### Screenshots:
Can't get a screenshot of like all 8 statuses...

### CODE REVIEW

**Comment by loreina** [comment]
Accepted:
image

Checked-in:
image

Confirmed:
image

Declined:
image

Waitlisted:
image

Withdrawn:
image

**Comment by RohitGarudadri** [comment]
Screen Shot 2020-01-14 at 8 09 02 PM

**Comment by loreina** [comment]
nit: can we have the buttons next to each other instead of stacked?

**Comment by RohitGarudadri** [comment]
Screen Shot 2020-01-15 at 10 23 07 AM

**Pull request merged**
