### PR TITLE
Redesign hackpass page

### PR DESCRIPTION
**Pull request by logan-r**
### Tickets:

- HCK-

### List of changes:

- Make hackpass page look better

What hackpass page [used to look like](https://gyazo.com/de31a89ed211bb6db971d93804679eb8)
What it looks like now:
screenshot

### Type of change:

- [x] New feature (non-breaking change which adds functionality)

### How did you do this?

- Updated page structure and css

### PR Checklist:

- [x] Merged `develop` branch (before testing)
- [x] Linted my code locally
- [x] Listed change(s) in the Changelog
- [x] Tested all links in project relevant browsers
- [x] Tested all links on different screen sizes
- [x] Referenced all useful info (issues, tasks, etc)

### Screenshots:
screenshot

### CODE REVIEW

**Comment by logan-r** [comment]
Thanks!

Yeah the downloaded pass pdf will be a separate PR

**Comment by pierreTklein** [comment]
Heads up ticket pdf redesign is a real pain, and should be done in conjunction with the sticker printer

**Comment by logan-r** [comment]
Oof thanks for the heads up!

**Comment by loreina** [comment]
Is this ready for merge?

**Pull request merged**
