### PR TITLE
fix where background image renders

### PR DESCRIPTION
**Pull request by RohitGarudadri**
### Tickets:

- HCK-

### List of changes:

-

### Type of change:

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### PR Checklist:

- [x] Merged `develop` branch (before testing)
- [x] Linted my code locally
- [x] Listed change(s) in the Changelog
- [x] Tested all links in project relevant browsers
- [x] Tested all links on different screen sizes
- [x] Referenced all useful info (issues, tasks, etc)

### CODE REVIEW

**Comment by logan-r** [comment]
This breaks the confirm email page, as it shouldn't have a background

**Comment by RohitGarudadri** [comment]
Ahh yeah, thats my bad, I thought I had moved it accidentally for a different task, so I moved it back to where I thought it belonged. Turns out I never actually moved that background image component😬

**Comment by logan-r** [comment]
Haha no worries man 😄

**Comment by loreina** [comment]
RIP @RohitGarudadri can you make a PR moving it back?

**Pull request merged**
